# Generated by Django 5.1.1 on 2024-09-09 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='usertype',
            field=models.CharField(blank=True, choices=[('conductor', 'Conductor'), ('owner', 'Owner'), ('admin', 'Admin')], max_length=30, null=True),
        ),
    ]
