# Generated by Django 5.1.1 on 2024-09-09 18:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_remove_record_bus_remove_record_recorder_record_bus_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='record',
            name='date',
            field=models.DateField(auto_created=True),
        ),
    ]
