# Generated by Django 5.1.1 on 2024-09-09 18:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_alter_record_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='record',
            name='date',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='record',
            name='time',
            field=models.TimeField(null=True),
        ),
    ]
